default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: sql-task-dev

test:
  <<: *default
  database: sql-task-test

production:
  <<: *default
  database: sql_task_prod
